from characters.Albedo import AlbedoTest
from characters.Amber import AmberTest
from characters.Beidou import BeidouTest
from characters.Bennett import BennettTest
from characters.Barbara import BarbaraTest
from characters.Chongyun import ChongyunTest
from characters.Diluc import DilucTest
from characters.Diona import DionaTest
from characters.Fischl import FischlTest
from characters.Ganyu import GanyuTest
from characters.Jean import JeanTest
from characters.Kaeya import KaeyaTest
from characters.Keqing import KeqingTest
from characters.Klee import KleeTest
from characters.Lisa import LisaTest
from characters.Mona import MonaTest
from characters.Noelle import NoelleTest
from characters.Ningguang import NingguangTest
from characters.Razor import RazorTest
from characters.Qiqi import QiqiTest
from characters.Tartaglia import TartagliaTest
from characters.Sucrose import SucroseTest
from characters.Traveler_Anemo import TravelerAnemoTest
from characters.Traveler_Geo import TravelerGeoTest
from characters.Xiangling import XianglingTest
from characters.Venti import VentiTest
from characters.Xiao import XiaoTest
from characters.Xingqiu import XingqiuTest
from characters.Xinyan import XinyanTest
from characters.Zhongli import ZhongliTest