from characters.Albedo import AlbedoF2P
from characters.Amber import AmberF2P
from characters.Barbara import BarbaraF2P
from characters.Beidou import BeidouF2P
from characters.Bennett import BennettF2P
from characters.Chongyun import ChongyunF2P
from characters.Diluc import DilucF2P
from characters.Diona import DionaF2P
from characters.Fischl import FischlF2P
from characters.Ganyu import GanyuF2P
from characters.Hutao import HutaoF2P
from characters.Jean import JeanF2P
from characters.Kaeya import KaeyaF2P
from characters.Keqing import KeqingF2P
from characters.Klee import KleeF2P
from characters.Lisa import LisaF2P
from characters.Mona import MonaF2P
from characters.Ningguang import NingguangF2P
from characters.Noelle import NoelleF2P
from characters.Qiqi import QiqiF2P
from characters.Razor import RazorF2P
from characters.Sucrose import SucroseF2P
from characters.Tartaglia import TartagliaF2P
from characters.Traveler_Anemo import TravelerAnemoF2P
from characters.Traveler_Geo import TravelerGeoF2P
from characters.Venti import VentiF2P
from characters.Xiangling import XianglingF2P
from characters.Xiao import XiaoF2P
from characters.Xingqiu import XingqiuF2P
from characters.Xinyan import XinyanF2P
from characters.Zhongli import ZhongliF2P
